// Generated by generate-variant-registry. Do not edit by hand.

use super::GeneratedVariant;

pub(super) const GENERATED_VARIANTS: &[GeneratedVariant] = &[
    GeneratedVariant {
        id: "BossECU_48",
        display_name: "BossECU 48 (STM32F4) / BossECU_48",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "EFIPRO",
        display_name: "EFIPRO (STM32F4) / EFIPRO",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "EFIPRO_H7",
        display_name: "EFIPRO H7 (STM32H7) / EFIPRO_H7",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "FCR_MicroF4",
        display_name: "FCR Micro F4 (STM32F429 / F407 bench variant) / FCR_MicroF4",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "KLM_BrainBoard",
        display_name: "KLM BrainBoard (STM32F7) / KLM_BrainBoard",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "KLM_ME3",
        display_name: "KLM ME3 (STM32F7) / KLM_ME3",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "KLM_MS43",
        display_name: "KLM MS43 (STM32F7) / KLM_MS43",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "M144F4RED",
        display_name: "M144 F4 Red (STM32F4) / M144F4RED",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "M144F7RED",
        display_name: "M144 F7 Red (STM32F7) / M144F7RED",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "M144H7BLACK",
        display_name: "M144 H7 Black (STM32H7) / M144H7BLACK",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "MEGA100F4",
        display_name: "MEGA 100 F4 (STM32F4) / MEGA100F4",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "MEGA100F429x16",
        display_name: "MEGA 100 F429 x16 (STM32F429) / MEGA100F429x16",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "MEGA100F4x16",
        display_name: "MEGA 100 F4 x16 (STM32F4) / MEGA100F4x16",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "MEGA144F7",
        display_name: "MEGA 144 F7 (STM32F7) / MEGA144F7",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "MEGA144H7",
        display_name: "MEGA 144 H7 (STM32H7) / MEGA144H7",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "MEGA144H7X20",
        display_name: "MEGA 144 H7 (STM32H7) / MEGA144H7X20",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "alphax-8chan",
        display_name: "Hellen AlphaX 8-channel (F4 / F7) / alphax-8chan",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "alphax-8chan_f7",
        display_name: "Hellen AlphaX 8-channel (F4 / F7) / alphax-8chan_f7",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "alphax-8chan_f7_debug",
        display_name: "Hellen AlphaX 8-channel (F4 / F7) / alphax-8chan_f7_debug",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "alphax-gold",
        display_name: "Hellen AlphaX Gold (STM32F7) / alphax-gold",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "alphax-silver",
        display_name: "Hellen AlphaX Silver (STM32F4) / alphax-silver",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "bossbrain_f427",
        display_name: "BossBrain F427 (STM32F429) / bossbrain_f427",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "epicECU",
        display_name: "epicECU (STM32F7) / epicECU",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "epicECUv1",
        display_name: "epicECU v1 (STM32H7) / epicECUv1",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "f407-discovery",
        display_name: "STM32F407 Discovery board / f407-discovery",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "f407-discoveryBIGFUEL",
        display_name: "STM32F407 Discovery BIGFUEL variant / f407-discoveryBIGFUEL",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "fcr_microf4_f407",
        display_name: "FCR Micro F4 (STM32F429 / F407 bench variant) / fcr_microf4_f407",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "fome_atlas",
        display_name: "FOME Atlas H7 / fome_atlas",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "hellen154hyundai",
        display_name: "Hellen 154 Hyundai (STM32F4) / hellen154hyundai",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "hellen154hyundai_f7",
        display_name: "Hellen 154 Hyundai (STM32F7) / hellen154hyundai_f7",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "hellen__uaefi__uaefi_pro_h7",
        display_name: "Hellen uaEFI family (F4 / F7 / H7, TCU) / uaefi_pro_h7",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "hellen__uaefibigfuel__uaefi_pro_h7",
        display_name: "Hellen uaEFI BIGFUEL family (F4 / F7 / H7) / uaefi_pro_h7",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "mre-legacy_f4",
        display_name: "MicroRusEFI (MRE) family (F4 / F7 / legacy F4) / mre-legacy_f4",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "mre_f4",
        display_name: "MicroRusEFI (MRE) family (F4 / F7 / legacy F4) / mre_f4",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "mre_f7",
        display_name: "MicroRusEFI (MRE) family (F4 / F7 / legacy F4) / mre_f7",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "paralela",
        display_name: "Paralela (STM32F4 / F429) / paralela",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "paralela427",
        display_name: "Paralela (STM32F4 / F429) / paralela427",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "proteus_f4",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_f4",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "proteus_f4_bigfuel",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_f4_bigfuel",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "proteus_f7",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_f7",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "proteus_f7_openblt",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_f7_openblt",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "proteus_f7_tcu",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_f7_tcu",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "proteus_h7",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_h7",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "proteus_h7_debug",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_h7_debug",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "proteus_legacy",
        display_name: "Proteus ECU family (F4/F7/H7) / proteus_legacy",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "simulator",
        display_name: "epicEFI simulator (host build, no MCU) / simulator",
        mcu_family: Some("simulator"),
    },
    GeneratedVariant {
        id: "super-uaefi",
        display_name: "Hellen Super uaEFI (STM32F7) / super-uaefi",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "tupperware",
        display_name: "Tupperware (STM32H7) / tupperware",
        mcu_family: Some("ARCH_STM32H7"),
    },
    GeneratedVariant {
        id: "uaefi",
        display_name: "Hellen uaEFI family (F4 / F7 / H7, TCU) / uaefi",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "uaefi-obd1",
        display_name: "Hellen uaEFI Honda OBD1 (STM32F4) / uaefi-obd1",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "uaefi-tcu",
        display_name: "Hellen uaEFI family (F4 / F7 / H7, TCU) / uaefi-tcu",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "uaefi121",
        display_name: "Hellen uaEFI 121 (STM32F4) / uaefi121",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "uaefiBIGFUEL",
        display_name: "Hellen uaEFI BIGFUEL family (F4 / F7 / H7) / uaefiBIGFUEL",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "uaefi_pro",
        display_name: "Hellen uaEFI family (F4 / F7 / H7, TCU) / uaefi_pro",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "uaefi_pro_bigfuel",
        display_name: "Hellen uaEFI BIGFUEL family (F4 / F7 / H7) / uaefi_pro_bigfuel",
        mcu_family: Some("ARCH_STM32F7"),
    },
    GeneratedVariant {
        id: "unit_tests",
        display_name: "Unit test harness (no MCU) / unit_tests",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "vthpnp",
        display_name: "VTH PnP (STM32F4) / vthpnp",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "xECU862",
        display_name: "Hellen xECU 862 (STM32F4) / xECU862",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "xECU862-bigfuel",
        display_name: "Hellen xECU 862 (STM32F4) / xECU862-bigfuel",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "zgrywus-k8",
        display_name: "Zgrywus K8 (STM32F4) / zgrywus-k8",
        mcu_family: Some("ARCH_STM32F4"),
    },
    GeneratedVariant {
        id: "zgrywus-ms43",
        display_name: "Zgrywus MS43 (STM32F4) / zgrywus-ms43",
        mcu_family: Some("ARCH_STM32F4"),
    },
];
