cpu:
  model: cortex-m7
  svd: STM32F767.svd
  vector_table: 0x00200000
regions:
  - name: ROM-ITCM-alias
    start: 0x00200000
    load: rusefi.bin
    size: 0x200000
  - name: ROM-AXI-alias
    start: 0x08000000
    load: rusefi.bin
    size: 0x200000
  - name: ITCM-RAM
    start: 0x00000000
    size: 0x4000
  - name: System-identifiers
    start: 0x1ff0f000
    size: 0x1000
  - name: DTCM-RAM
    start: 0x20000000
    size: 0x20000
  - name: SRAM1
    start: 0x20020000
    size: 0x5c000
  - name: SRAM2
    start: 0x2007c000
    size: 0x4000
devices:
  usb_cdc_tcp:
    - peripheral: OTG_FS_GLOBAL
      listen: 127.0.0.1:29000
      max_buffered_bytes: 65536
  ecu_io:
    - listen: 127.0.0.1:29002
      pins:
        - { name: crank, pin: PC6, direction: input }
        - { name: cam,   pin: PE11, direction: input }
        - { name: inj1,  pin: PD7, direction: output }
        - { name: ign1,  pin: PD4, direction: output }
      adc_channels:
        - { name: map, pin: PC0 }
        - { name: tps, pin: PC1 }
        - { name: clt, pin: PB0 }
        - { name: iat, pin: PC5 }
        - { name: vbatt, pin: PA7 }
